config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: { registrations: 'registrations' }

  root 'dashboard#index'

  resources :dashboard

  resources :users do
    resources :exercises
  end

  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
    end
  end

  resources :friendships, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user

  validates :duration_in_min, presence: true
  validates :duration_in_min, numericality: { only_integer: true }
  validates :workout, presence: true
  validates :workout_date, presence: true
  validates :user_id, presence: true

  default_scope { where('workout_date > ?', 7.days.ago).order(workout_date: :desc) }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :exercises
  has_many :friendships
  has_many :friends, through: :friendships, class_name: 'User'

  validates :first_name, presence: true
  validates :last_name, presence: true

  self.per_page = 10

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.search_by_name(name)
    names_array = name.split(' ')

    if names_array.size == 1
      where('first_name ILIKE ? or last_name ILIKE ?', "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name ILIKE ? or first_name ILIKE ? or last_name ILIKE ? or last_name ILIKE ?',
            "%#{names_array[0]}%", "%#{names_array[1]}%", "%#{names_array[0]}%", "%#{names_array[1]}%").order(:first_name)
    end
  end

  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) || self == new_friend
  end

  def current_friendship(friend)
    friendships.where(friend: friend).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    user_attr = [:first_name, :last_name, :email, :password, :password_confirmation]

    devise_parameter_sanitizer.permit :account_update, keys: user_attr
    devise_parameter_sanitizer.permit :sign_up, keys: user_attr
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @athletes = User.paginate(page: params[:page])
  end

  def search
    @athletes = User.search_by_name(params[:search_name]).paginate(page: params[:page])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = current_user.exercises.all
    @friends = current_user.friends
  end

  def show
  end

  def new
    @exercise = current_user.exercises.new
  end

  def create
    @exercise = current_user.exercises.new(exercise_params)

    if @exercise.save
      flash[:success] = 'Exercise has been created'
      redirect_to [current_user, @exercise]
    else
      flash[:danger] = 'Exercise has not been created'
      render :new
    end
  end

  def edit
  end

  def update
    if @exercise.update(exercise_params)
      flash[:success] = 'Exercise has been updated'
      redirect_to [current_user, @exercise]
    else
      flash[:danger] = 'Exercise has not been updated'
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    flash[:success] = 'Exercise has been deleted'
    redirect_to user_exercises_path(current_user)
  end

  private

  def exercise_params
    params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
  end

  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def show
    @friend = Friendship.find(params[:id]).friend
    @exercises = @friend.exercises.all
  end

  def create
    friend = User.find(params[:friend_id])
    Friendship.create(friendship_params.merge!(friend_id: params[:friend_id],
                                               user_id: current_user.id)) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    if @friendship.destroy
      flash[:success] = "#{@friendship.friend.full_name} unfollowed"
    else
      flash[:danger] = "#{@friendship.friend.full_name} could not be unfollowed"
    end

    redirect_to user_exercises_path(current_user)
  end

  private

  def friendship_params
    params.permit(:friend_id, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboard/index.html.erb
<h1 class="text-center">Workout Lounge</h1>

<h2>List of members</h2>

<% @athletes.each do |ath| %>
  <%= ath.first_name %>
  <%= ath.last_name %>

  <% if current_user %>
    <%= link_to 'Follow', friendships_path(friend_id: ath.id), method: :post,
                          class: 'btn btn-primary' unless current_user.follows_or_same?(ath) %>
  <% end %>
  <hr>
<% end %>

<%= will_paginate @athletes, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/dashboard/search.html.erb
<% @athletes.each do |ath| %>
  <%= ath.first_name %>
  <%= ath.last_name %>
<% end %>

app/views/exercises/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for([current_user, @exercise], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @exercise.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved: </h2>

          <ul>
            <% @exercise.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :duration_in_min, "Duration (min)" %>
        </div>

        <div class="col-md-10">
          <%= f.number_field :duration_in_min, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Workout details" %><br>
        </div>

        <div class="col-md-10">
          <%= f.text_area :workout, class: "form-control", rows: "10" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout_date, "Activity date" %>
        </div>

        <div class="col-md-10">
          <%= f.text_field :workout_date, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit 'Create exercise', class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/edit.html.erb
<h1 class="text-center">Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', [current_user, @exercise] %>

<%= link_to 'Back', user_exercises_path(current_user) %>

app/views/exercises/index.html.erb
<% @exercises.each do |exercise| %>
  <%= exercise.duration_in_min %>
  <%= exercise.workout %>
  <%= exercise.workout_date %>

  <%= link_to 'Show workout', user_exercise_path(current_user, exercise) %>
  <%= link_to 'Edit workout', edit_user_exercise_path(current_user, exercise) %>
  <%= link_to 'Destroy', user_exercise_path(current_user, exercise), method: :delete %>
  <hr>
<% end %>

<%= link_to 'New workout', new_user_exercise_path(current_user), class: 'btn btn-primary' %>

<%= content_tag :div, '', id: 'chart', data: { workouts: @exercises } %>

<h1 class="text-center">My friends</h1>

<% @friends.each do |friend| %>
  <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
  <%= link_to 'Unfollow', friendship_path(current_user.current_friendship(friend)), method: :delete,
                                          class: 'btn btn-danger'%>
<% end %>

app/views/exercises/new.html.erb
<h1 class="text-center">New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', user_exercises_path(current_user), class: 'btn btn-secondary' %>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">

  <div>
    <h2 class="show-header">Workout Details</h2>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>

    <div class="col-xs-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout details:</strong>
    </div>

    <div class="col-xs-8 text-right">
      <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity date:</strong>
    </div>

    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>

  <br>

  <div class="col-xs-12 col-md-10 member">
    <%= link_to "Back", user_exercises_path(current_user), class: 'btn btn-secondary' %>
  </div>
</div>

app/views/friendships/show.html.erb
<%= notice %>

<h1><%= @friend.full_name %>'s exercises</h1>

<% @exercises.each do |exercise| %>
  <%= exercise.duration_in_min %>
  <%= truncate(exercise.workout, length: 100) %>
  <%= exercise.workout_date %>
<% end %>

<%= content_tag :div, '', id: 'chart', data: { workouts: @exercises } %>

<%= link_to 'Back', user_exercises_path(current_user), class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/header' %>

      <br>

      <% flash.each do |key, msg| %>
        <div class='alert'>
          <a href="#" class='close' data-dismiss="alert">&#215;</a>
          <b><%= msg %></b>
        </div>
      <% end %>

      <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Athletes Den', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My lounge', user_exercises_path(current_user), class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>

        <%= form_tag(search_dashboard_path, class: 'navbar-form navbar-left', role: 'search') do %>
          <%= text_field_tag :search_name, params[:search_name], placeholder: 'Search for friends', class: 'form-control' %>
          <%= submit_tag 'Search', class: 'btn btn-default' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>